Multiplex gentx
dydxprotocol/v4-testnets pull request #41
Opened 2023-10-12 09:17 UTC by Multiplex-Lab

2023-10-12 09:31 UTC, 2dpetkov requested changes

2023-10-12 09:31 UTC, 2dpetkov commented on dydx-testnet-4/gentx/gentx-Multiplex.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Multiplex","identity":"","website":"https://multiplexlabs.xyz/","security_contact":"","details":"M
the [Prepare for Genesis](https://v4-teacher.vercel.app/validators/preparing_for_genesis) guide is a little different this time, the test token is `adv4tnt` and the self-delegation amount is `500000000000000000000000adv4tnt`

2023-10-12 19:08 UTC, 2dpetkov commented on dydx-testnet-4/gentx/gentx-Multiplex.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Multiplex","identity":"","website":"https://multiplexlabs.xyz/","security_contact":"","details":"M
@Multiplex-Lab kind reminder

2023-10-13 11:41 UTC, Multiplex-Lab reviewed
Fix

2023-10-13 11:46 UTC, 2dpetkov commented on dydx-testnet-4/gentx/gentx-Multiplex.json
> +{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Multuplex","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"1.
Please confirm if this is correct
`"moniker":"Multuplex"`

2023-10-13 11:52 UTC, Multiplex-Lab commented
Fixd

2023-10-13 12:20 UTC, Multiplex-Lab commented
Repair once again, thank you for your patience and understanding.

2023-10-13 12:48 UTC, 2dpetkov approved these changes

2023-10-13 12:48 UTC, merged

2023-10-13 12:48 UTC, 2dpetkov commented
no worries!